from __future__ import annotations


def get_schema_sql(dialect: str) -> str:
    if dialect == "postgresql":
        return POSTGRES_SCHEMA_SQL
    return SQLITE_SCHEMA_SQL


SQLITE_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS cenarios (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    descricao TEXT,
    criado_em TEXT DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS ambientes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cenario_id INTEGER NOT NULL,
    nome TEXT NOT NULL,
    tipo_ambiente TEXT,
    observacoes TEXT,
    FOREIGN KEY(cenario_id) REFERENCES cenarios(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS equipamentos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    ambiente_id INTEGER NOT NULL,
    nome TEXT NOT NULL,
    tipo_equipamento TEXT,
    potencia_kw REAL,
    quantidade INTEGER,
    prob_uso_base REAL,
    duracao_base_h REAL,
    ciclos_por_dia_base REAL,
    fator_carga_base REAL,
    observacoes TEXT,
    FOREIGN KEY(ambiente_id) REFERENCES ambientes(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS janelas_uso (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    equipamento_id INTEGER NOT NULL,
    inicio_hora INTEGER,
    fim_hora INTEGER,
    prioridade INTEGER DEFAULT 1,
    tipo_janela TEXT DEFAULT 'preferencial',
    FOREIGN KEY(equipamento_id) REFERENCES equipamentos(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS perfis_consumo (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    tipo_equipamento TEXT,
    categoria TEXT,
    descricao TEXT,
    parametros_json TEXT
);
CREATE TABLE IF NOT EXISTS perfis_sazonais (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT NOT NULL,
    tipo_equipamento TEXT,
    descricao TEXT,
    fatores_json TEXT
);
CREATE TABLE IF NOT EXISTS associacao_perfil_equipamento (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    equipamento_id INTEGER NOT NULL,
    perfil_consumo_id INTEGER,
    perfil_sazonal_id INTEGER,
    FOREIGN KEY(equipamento_id) REFERENCES equipamentos(id) ON DELETE CASCADE,
    FOREIGN KEY(perfil_consumo_id) REFERENCES perfis_consumo(id),
    FOREIGN KEY(perfil_sazonal_id) REFERENCES perfis_sazonais(id)
);
CREATE TABLE IF NOT EXISTS simulacoes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cenario_id INTEGER NOT NULL,
    nome TEXT NOT NULL,
    mes_referencia TEXT,
    numero_iteracoes INTEGER,
    passo_temporal_min INTEGER,
    seed INTEGER,
    criado_em TEXT DEFAULT CURRENT_TIMESTAMP,
    parametros_json TEXT,
    FOREIGN KEY(cenario_id) REFERENCES cenarios(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS resultados_simulacao (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    simulacao_id INTEGER NOT NULL,
    demanda_pico_kw REAL,
    demanda_media_kw REAL,
    energia_kwh_estimada REAL,
    mes_critico INTEGER,
    resultados_json TEXT,
    FOREIGN KEY(simulacao_id) REFERENCES simulacoes(id) ON DELETE CASCADE
);
"""

POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS cenarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    descricao TEXT,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ DEFAULT NOW()
);
CREATE TABLE IF NOT EXISTS ambientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cenario_id BIGINT NOT NULL REFERENCES cenarios(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    tipo_ambiente TEXT,
    observacoes TEXT
);
CREATE TABLE IF NOT EXISTS equipamentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ambiente_id BIGINT NOT NULL REFERENCES ambientes(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    tipo_equipamento TEXT,
    potencia_kw DOUBLE PRECISION,
    quantidade INTEGER,
    prob_uso_base DOUBLE PRECISION,
    duracao_base_h DOUBLE PRECISION,
    ciclos_por_dia_base DOUBLE PRECISION,
    fator_carga_base DOUBLE PRECISION,
    observacoes TEXT
);
CREATE TABLE IF NOT EXISTS janelas_uso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipamento_id BIGINT NOT NULL REFERENCES equipamentos(id) ON DELETE CASCADE,
    inicio_hora INTEGER,
    fim_hora INTEGER,
    prioridade INTEGER DEFAULT 1,
    tipo_janela TEXT DEFAULT 'preferencial'
);
CREATE TABLE IF NOT EXISTS perfis_consumo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    tipo_equipamento TEXT,
    categoria TEXT,
    descricao TEXT,
    parametros_json TEXT
);
CREATE TABLE IF NOT EXISTS perfis_sazonais (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome TEXT NOT NULL,
    tipo_equipamento TEXT,
    descricao TEXT,
    fatores_json TEXT
);
CREATE TABLE IF NOT EXISTS associacao_perfil_equipamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipamento_id BIGINT NOT NULL REFERENCES equipamentos(id) ON DELETE CASCADE,
    perfil_consumo_id BIGINT REFERENCES perfis_consumo(id),
    perfil_sazonal_id BIGINT REFERENCES perfis_sazonais(id)
);
CREATE TABLE IF NOT EXISTS simulacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cenario_id BIGINT NOT NULL REFERENCES cenarios(id) ON DELETE CASCADE,
    nome TEXT NOT NULL,
    mes_referencia TEXT,
    numero_iteracoes INTEGER,
    passo_temporal_min INTEGER,
    seed INTEGER,
    criado_em TIMESTAMPTZ DEFAULT NOW(),
    parametros_json TEXT
);
CREATE TABLE IF NOT EXISTS resultados_simulacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simulacao_id BIGINT NOT NULL REFERENCES simulacoes(id) ON DELETE CASCADE,
    demanda_pico_kw DOUBLE PRECISION,
    demanda_media_kw DOUBLE PRECISION,
    energia_kwh_estimada DOUBLE PRECISION,
    mes_critico INTEGER,
    resultados_json TEXT
);
"""
